# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Apr 10 15:55:28 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 685)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.sourceButton = QtGui.QPushButton(self.centralWidget)
        self.sourceButton.setGeometry(QtCore.QRect(202, 9, 75, 23))
        self.sourceButton.setObjectName("sourceButton")
        self.sourceEdit = QtGui.QLineEdit(self.centralWidget)
        self.sourceEdit.setGeometry(QtCore.QRect(301, 10, 391, 20))
        self.sourceEdit.setObjectName("sourceEdit")
        self.addButton = QtGui.QPushButton(self.centralWidget)
        self.addButton.setGeometry(QtCore.QRect(710, 20, 75, 23))
        self.addButton.setObjectName("addButton")
        self.destinationButton = QtGui.QPushButton(self.centralWidget)
        self.destinationButton.setGeometry(QtCore.QRect(202, 38, 75, 23))
        self.destinationButton.setObjectName("destinationButton")
        self.tableView = QtGui.QTableView(self.centralWidget)
        self.tableView.setGeometry(QtCore.QRect(202, 67, 581, 291))
        self.tableView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableView.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setVisible(False)
        self.editButton = QtGui.QPushButton(self.centralWidget)
        self.editButton.setEnabled(False)
        self.editButton.setGeometry(QtCore.QRect(400, 368, 75, 23))
        self.editButton.setObjectName("editButton")
        self.destinationEdit = QtGui.QLineEdit(self.centralWidget)
        self.destinationEdit.setGeometry(QtCore.QRect(301, 39, 391, 20))
        self.destinationEdit.setObjectName("destinationEdit")
        self.syncAllButton = QtGui.QPushButton(self.centralWidget)
        self.syncAllButton.setGeometry(QtCore.QRect(710, 370, 75, 23))
        self.syncAllButton.setObjectName("syncAllButton")
        self.syncButton = QtGui.QPushButton(self.centralWidget)
        self.syncButton.setEnabled(False)
        self.syncButton.setGeometry(QtCore.QRect(202, 368, 75, 23))
        self.syncButton.setObjectName("syncButton")
        self.deleteButton = QtGui.QPushButton(self.centralWidget)
        self.deleteButton.setEnabled(False)
        self.deleteButton.setGeometry(QtCore.QRect(301, 368, 75, 23))
        self.deleteButton.setObjectName("deleteButton")
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 74))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 74))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 74))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 74))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 74))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.treeView = QtGui.QTreeView(self.centralWidget)
        self.treeView.setGeometry(QtCore.QRect(10, 410, 341, 271))
        self.treeView.setObjectName("treeView")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(640, 410, 341, 241))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtGui.QWidget()
        self.Home.setObjectName("Home")
        self.tabWidget.addTab(self.Home, "")
        self.MapFolder = QtGui.QWidget()
        self.MapFolder.setObjectName("MapFolder")
        self.tabWidget.addTab(self.MapFolder, "")
        self.status = QtGui.QLabel(self.centralWidget)
        self.status.setGeometry(QtCore.QRect(390, 420, 132, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setText("")
        self.status.setPixmap(QtGui.QPixmap("C:/Users/Ibis/PycharmProjects/Backup/Status.png"))
        self.status.setObjectName("status")
        self.status_2 = QtGui.QLabel(self.centralWidget)
        self.status_2.setGeometry(QtCore.QRect(390, 480, 132, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_2.sizePolicy().hasHeightForWidth())
        self.status_2.setSizePolicy(sizePolicy)
        self.status_2.setText("")
        self.status_2.setPixmap(QtGui.QPixmap("C:/Users/Ibis/PycharmProjects/Backup/Statistics.png"))
        self.status_2.setObjectName("status_2")
        #MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Ibis Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceButton.setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.destinationButton.setText(QtGui.QApplication.translate("MainWindow", "Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.editButton.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.syncAllButton.setText(QtGui.QApplication.translate("MainWindow", "Sync All", None, QtGui.QApplication.UnicodeUTF8))
        self.syncButton.setText(QtGui.QApplication.translate("MainWindow", "Start Sync", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Map Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), QtGui.QApplication.translate("MainWindow", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MapFolder), QtGui.QApplication.translate("MainWindow", "Map Folder", None, QtGui.QApplication.UnicodeUTF8))

